### ISSUE TITLE
Mismatch Detection message is very fast

### ISSUE THREAD

**Issue by Robmonster** [Hyper-Dragon/DgtAngel#18]
I've found that the mismatch detection voice message is very fast to be played. If I don't make the opponents move almost immediately on the board then the mismatch detection / mismatch resolved messages get played.

Perhaps this could be tweakable via a setting, or have a longer grace period for the message to trigger.

Perhaps if the move isn't made at all it should repeat the opponent move announcement at a certain frequency, and save the mismatch detection message for when you've played the wrong opponents move

**Comment by Hyper-Dragon** [comment]
The grace period was previously a bit longer but I agree that it should be configurable.  I like the idea of repeating the move announcement so will look into it.  Saving the mismatch detection message for the wrong move would be good but difficult to implement because it works on the board state, not individual moves (you can move the pieces in any order and the mismatch detection will still work).

**Comment by Hyper-Dragon** [comment]
Complete in ver 0.1.0
