### ISSUE TITLE
Own move not announced if opponent premoves

### ISSUE THREAD

**Issue by dlbbld** [Hyper-Dragon/DgtAngel#77]
Usually, when I make a move on the DGT board, like Bc4, the software announces the move, "Bishop c4". That is indeed also helpful to check if my move was registered.

But if my opponent already premoved, that is not the case.

Example: I play e4, and the software announces e4. The opponent replies with e5, and the software announces e5. The opponent now premoves Nf6. I play Bc4, but the software does not announce Bc4. The next move it announces is Nf6.

**Comment by Hyper-Dragon** [comment]
I think this may be a feature, not a bug 😉.

In early development all moves were vocalised.  The problem with this is that it takes longer to say a move vs. make a move (frustrating in practice).  Essentially, the Bc4 voice is dropped from the audio queue because the Nf6 has arrived before it has started reading it.  This is by design and it sounds like what is happening here.

An option could be added to read all moves but I am two minds about that.  Thoughts?

**Comment by dlbbld** [comment]
Thinking about this again, I don't need my moves announced. I prefer a quick sound confirming move registration, for it takes less time anyway and avoids the situation. So yes, one can look at skipping move announcements as a feature. However, I'm not too fond of different behavior depending on my opponent's play speed. Premoves occur often. So a quick but unconditional sound after move registration would also be fine.

As an idea, one could also play a slightly different quick sound to confirm the correct opponent move replay. The Acid Ape Chess software provides both sounds, which I like.

**Comment by Hyper-Dragon** [comment]
Added 'player beep' option.  When checked the move made by the player is no longer read but instead a beep is heard (I actually prefer this now 👍).  The 'move in' queue length has been increased so when this option is enabled pre-moves are voiced.
